### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by GoogeTan** [nikita-volkov/strelka-helloworld#1]
Non changed and empty project causes build error:
[strelka-1-8c1552d42c15c781ad741713fe718ae3229a8901a5fb402a7e729e28021d1a35.log](https://github.com/nikita-volkov/strelka-helloworld/files/9274867/strelka-1-8c1552d42c15c781ad741713fe718ae3229a8901a5fb402a7e729e28021d1a35.log)

**Comment by nikita-volkov** [comment]
Sorry. This project is deprecated. I've marked it so.
